### ISSUE TITLE
See the photo before save it

### ISSUE THREAD

**Issue by lauropaixao** [yasirkula/UnityNativeGallery#10]
Hello There, 

I am working on an app thats should take a photo and, before save it, show it and then the users can decide if they want to keep and share or delete.

For do this using NativeGallery.GetImageFromGallery I should know the name of the last photo taken, am I right?

Do you have any tips for how can I do this? Is there a function that show the photo after take it?

Thanks in advance for your help.

!!! Best Regards !!!

Lauro Paixão

**Comment by yasirkula** [comment]
Hi Lauro,

GetImageFromGallery prompts the user to pick an existing image from the gallery. I don't think that is what you are looking for.

If you want to capture a screenshot from your game and show it to the user, you can use the TakeScreenshotAndSave() function in the example code. But rather than saving it to gallery immediately, show it on a RawTexture object (you can assign the Texture2D to its *texture* property).

If you are trying to take a photo using the phone's camera, then you should be using a plugin that lets you access the device camera. After the photo is taken, you should be able to retrieve it as a Texture2D using the same plugin and then, you can show the Texture2D on a RawTexture and, if you want, use the `NativeGallery.SaveImageToGallery( Texture2D image, string album, string filenameFormatted )` function to save it to the gallery.

**Comment by lauropaixao** [comment]
Hi Yasir,

Thanks for a fast answer. I'll try it and let you know !!!
