### ISSUE TITLE
Unity restarting after picking img

### ISSUE THREAD

**Issue by adrianjmejias** [yasirkula/UnityNativeGallery#100]
Just as the title says, I pick an image and it restarts unity.

 I'm not limiting the size of the picture but It's only a small camera picture.

Is there any fix to this?

**Comment by yasirkula** [comment]
On which device is this happening?

**Comment by adrianjmejias** [comment]
Xiomi mi A2 lite

**Comment by yasirkula** [comment]
NativeGallery and NativeCamera use Android Fragments to display native content. If device runs low on memory while the native content is being displayed, Android OS can close background activities to release some memory. It is possible for OS to close Unity activity as well, since it is considered a background activity while the native content is being displayed. This might be one cause of this issue. Try closing all background apps before testing the app.

Do other phones also suffer from this issue? If so, please check logcat for any meaningful error messages.

**Comment by adrianjmejias** [comment]
umm It is as you say. I picked a screenshot and It worked just fine.
It's a memory issue..
