### ISSUE TITLE
Native Gallery Get Save Path Does Not Exist

### ISSUE THREAD

**Issue by kashifalimizo** [yasirkula/UnityNativeGallery#124]
'NativeGallery' does not contain a definition for 'GetSavePath'

**Comment by yasirkula** [comment]
Yes it doesn't 😄 NativeGallery doesn't support retrieving the path of the saved image.

**Comment by drlecks** [comment]
In fact, it had this feature. 

I was using this function since 2018 to retrieve the gallery save path and fetch all the images in it. I have a "private gallery" in my app that only shows my photos. My app is only available on Android.

Today I updated the plugin and the method just disappeared from there.

Here is the missing method:
 ```

public static string GetSavePath( string album, string filenameFormatted )
	{
		string saveDir;
#if !UNITY_EDITOR && UNITY_ANDROID
		saveDir = AJC.CallStatic<string>( "GetMediaPath", album );
#else
		saveDir = Application.persistentDataPath;
#endif

		if( filenameFormatted.Contains( "{0}" ) )
		{
			int fileIndex = 0;
			string path;
			do
			{
				path = Path.Combine( saveDir, string.Format( filenameFormatted, ++fileIndex ) );
			} while( File.Exists( path ) );

			return path;
		}

		saveDir = Path.Combine( saveDir, filenameFormatted );

#if !UNITY_EDITOR && UNITY_IOS
		// iOS internally copies images/videos to Photos directory of the system,
		// but the process is async. The redundant file is deleted by objective-c code
		// automatically after the media is saved but while it is being saved, the file
		// should NOT be overwritten. Therefore, always ensure a unique filename on iOS
		if( File.Exists( saveDir ) )
		{
			return GetSavePath( album,
				Path.GetFileNameWithoutExtension( filenameFormatted ) + " {0}" + Path.GetExtension( filenameFormatted ) );
		}
#endif

		return saveDir;
	} 
```

It's the only way I found to achieve this feature. And now I have to "close" the gallery to publish a critical update on the store.

**Comment by yasirkula** [comment]
I've explained the reason in [FAQ](https://github.com/yasirkula/UnityNativeGallery#faq). But it seems like Storage Access Framework will [no longer be mandatory with the release of Android 11](https://developer.android.com/preview/privacy/storage#media-direct-file-native). Thus, I may add something similar to GetSavePath in the future.

At the moment, if GetSavePath is mandatory for you, you can revert to the older NativeGallery version from your version control system (preferred way) or via [this unitypackage](https://github.com/yasirkula/UnityNativeGallery/blob/ad14dd4d8d44f3c3ee60a5f649b7faa0b38c804d/NativeGallery.unitypackage) (it's the latest version with GetSavePath).

**Comment by drlecks** [comment]
Thanks for the quick reply. I imagined that android version changes were relatiined with the removal of this feature. And yes, it would be very useful to have something similar back!

Rolling back to previous versions is bot an option for me. I had to update because I had a rare bug in few devices when picking images from gallery it just did nothing when returning to the app. I'm still monitoring my update, but seems that latest version solves the problem.

**Comment by yasirkula** [comment]
With the [latest release](https://github.com/yasirkula/UnityNativeGallery/commit/84ac70d7e04088dbc166a58b5d26bbd5ea219170), MediaSaveCallback now returns a `string path` parameter (Android only). However, if the raw filepath can't be determined, an abstract Storage Access Framework path will be returned (File.Exists returns false for that path).
