### ISSUE TITLE
Is possible to make a gallery by using UGUI?

### ISSUE THREAD

**Issue by qtghost** [yasirkula/UnityNativeGallery#128]
I tried a lot of method , like native send photo paths , then unity read bytes , but it doesnt work fluently
@yasirkula Do you have any ideas ? thanks.

**Comment by yasirkula** [comment]
I'd do it your way, as well. But instead of reading all the bytes and generating a full-resolution image, I'd use NativeGallery.LoadImageAtPath with a small maxSize to create only a thumbnail image to display in Gallery.

To eliminate the lag, textures may have to be generated on a separate thread. AFAIK, Unity doesn't allow that with managed code. So you'd have to create the textures in your native Android code and pass them to Unity but I've no experience with that.

**Comment by qtghost** [comment]
> I'd do it your way, as well. But instead of reading all the bytes and generating a full-resolution image, I'd use NativeGallery.LoadImageAtPath with a small maxSize to create only a thumbnail image to display in Gallery.
> 
> To eliminate the lag, textures may have to be generated on a separate thread. AFAIK, Unity doesn't allow that with managed code. So you'd have to create the textures in your native Android code and pass them to Unity but I've no experience with that.

okay , thanks !
