### ISSUE TITLE
Updating to new Version

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeGallery#142]
Previously I updated to 1.5.0 and now to 1.6.0. 

In every case I need to make some changes to code because compile errors.

Please when it is possible before releasing, create overridden methods with default parameters to resolve such situations.

P.S. NativeGallery.CheckPermission(); & NativeGallery.RequestPermission(); is example of this situation for 1.6.0. Now there is a parameter.

**Comment by yasirkula** [comment]
In this case, it was necessary to have a PermissionType parameter. On iOS, the corresponding PermissionType **must be** passed to the CheckPermission and RequestPermission functions to display the correct permission dialog and I can't guess PermissionType when a default parameter is used.

I try to make these backwards-incompatible changes as rarely as possible, though. Thank you for your concern.

**Comment by andrewio** [comment]
> In this case, it was necessary to have a PermissionType parameter. On iOS 14+, the corresponding PermissionType **must be** passed to the CheckPermission and RequestPermission functions to display the correct permission dialog and I can't guess PermissionType when a default parameter is used.
> 
> I try to make these backwards-incompatible changes as rarely as possible, though. Thank you for your concern.

Write Permission was as default before as I guess.

**Comment by yasirkula** [comment]
Yes, `Write Permission > Read Permission` on Android and the permission type didn't matter before iOS 14, so it used to be fine. On iOS 14+, `Read Permission > Write Permission` so I must know the permission type.

**Comment by andrewio** [comment]
> Yes, `Write Permission > Read Permission` on Android and the permission type didn't matter before iOS 14, so it used to be fine. On iOS 14+, `Read Permission > Write Permission` so I must know the permission type.

For iOS 14+ I said "hmm....". If here I granted "Read" then "Write" is already included?

My app writes and reads to & from gallery on both iOS & Android. So I need max permissions. So I need to use compiler directives (#if) separately to iOS (Read) & Android (Write). Is it correct?

**Comment by yasirkula** [comment]
Normally, if I was asking Read permission on iOS 14+, yes it would include Write permission. However, I don't ask Read permission at all on iOS 11+ because it is not needed. That also helps us avoid an issue with Apple's new Photos permission system in iOS 14+: due to how NativeGallery handles the permissions synchronously (even though the permissions are asked asynchronously in the background), when user clicks "Select Photos" option in the new permission dialog, their app will freeze, a deadlock will happen.

So you really must ask Read permission for Get operations and Write permission for Save operations.
