### ISSUE TITLE
How rotate a texture when it's saving.

### ISSUE THREAD

**Issue by keybook2016** [yasirkula/UnityNativeGallery#145]
Your function has been helped me too much! thank you, but for webcamtexture, the texture always turn to -90, could we rotate the texture when we save the image to phone.

**Comment by yasirkula** [comment]
NativeGallery can't rotate a Texture2D because Texture2Ds don't have a rotation information. Since it can't rotate textures, I haven't implemented any functions to rotate Texture2Ds. You must rotate the Texture2D yourself using the rotation information from webcam and then save that rotated Texture2D to the Gallery.

**Comment by keybook2016** [comment]
Thank you, Yasirkula! I wish you could increase this function to your program if you have time. And now I just rotate the image from a plane then got the texture again.
