### ISSUE TITLE
On ios14.0.1, part image permissions not work

### ISSUE THREAD

**Issue by CUTEQWQ** [yasirkula/UnityNativeGallery#177]
On ios14.0.1, i can assess all images in gallery although i only allow part permissions of them.
And I'm sure i has updated the plugin.

**Comment by yasirkula** [comment]
If "Select Photos" option appeared in permissions dialog, it shouldn't have. You need to update Xcode to at least Xcode 12 and target the latest iOS version.

**Comment by CUTEQWQ** [comment]
> If "Select Photos" option appeared in permissions dialog, it shouldn't have. You need to update Xcode to at least Xcode 12 and target the latest iOS version.

My Xcode version is already 12. I choose "Select Photos" option and select some of them, but I have permission of all gallery....

**Comment by yasirkula** [comment]
That's the thing, I've coded it so that "Select Photos" permission won't appear. Other users have reported that it is working for them on Xcode 12, so I'm not sure why it isn't working for you. I'm also not sure why "Select Photos" doesn't crash the game in your case. Are you using another plugin to request Photos permission? If not, does setting target iOS level to at least 14 get rid of the "Select Photos" permission?

**Comment by CUTEQWQ** [comment]
> That's the thing, I've coded it so that "Select Photos" permission won't appear. Other users have reported that it is working for them on Xcode 12, so I'm not sure why it isn't working for you. I'm also not sure why "Select Photos" doesn't crash the game in your case. Are you using another plugin to request Photos permission? If not, does setting target iOS level to at least 14 get rid of the "Select Photos" permission?

yeah, maybe because I mixed use another plugin and this plguin to check and request permission, and the other one not support ios 14, so actually it has all permissions?
And, can i ask the reason why they crash when click "Select Photos" option?

**Comment by yasirkula** [comment]
NativeGallery asks permissions synchronously by locking the Unity thread but "Select Photos" permission doesn't support it so it hangs and crashes.

If you wish to continue using the other plugin, it is safe to ignore this "Select Photos" behaviour. Even though "Select Photos" option is picked, NativeGallery will show the whole Photos album because no permission is needed to fetch images from Photos on iOS 11+.

**Comment by CUTEQWQ** [comment]
> NativeGallery asks permissions synchronously by locking the Unity thread but "Select Photos" permission doesn't support it so it hangs and crashes.
> 
> If you wish to continue using the other plugin, it is safe to ignore this "Select Photos" behaviour. Even though "Select Photos" option is picked, NativeGallery will show the whole Photos album because no permission is needed to fetch images from Photos on iOS 11+.

Got, thanks very much!!
