### ISSUE TITLE
Deny storage permission not working as expected in Android 11

### ISSUE THREAD

**Issue by sanathkukkillaya** [yasirkula/UnityNativeGallery#183]
**Description of the bug**

This is not exactly a bug, but I would like a bit of clarification here since the functionality is not exactly what I expected. I use this plugin to save images and videos to the gallery. As necessary, I do a CheckPermission before I try to save. When the permission is granted, this function returns me Permission.Granted.

The problem is that while testing, I denied the permission to app. Yet the CheckPermission method still returns Permission.Granted, and I am actually able to save the image/video. While this is not an issue, since my main goal is to save the image/video, however I am a bit unsure as to how this works. Because the user has explicitly denied permission, ideally, shouldn't I not be able to save?

I did come across this statement in the readme: `Note that NativeGallery doesn't require any permissions for picking images/videos from Photos on iOS 11+ and saving images/videos to Gallery on Android 29+, so no permission dialog will be shown in these cases and the permission functions will return Permission.Granted.` So going by this, if I can save without permission, why should I bother asking for permission in the first place?

Can you please let me know if this is correct? My QA team will definitely raise an issue, since on denying permission, user should not be able to save to the device.

I haven't been able to test on iOS yet. Not sure if this happens similarly in iOS as well.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2019.3.5f1*
- Platform: *Android, iOS*
- Device: *Redmi K20 with a PixelExperience rom*

**Comment by yasirkula** [comment]
The same thing won't happen on iOS while saving media.

As you can see in the native code, the Storage permission isn't queried at all on Android 10+ because it isn't needed: https://github.com/yasirkula/UnityNativeGallery/blob/d42e281c5afd47ab4dcb5bf86c9773b251f204d7/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeGallery.java#L324-L331

You need to continue checking the permission because users on Android 9 or earlier will need that permission. If the issue you are having is the Storage permission being asked automatically when the app is launched for the first time, that's Unity's doing (see [Runtime Permissions](https://docs.unity3d.com/Manual/android-manifest.html)).

If you don't need WRITE_EXTERNAL_STORAGE permission elsewhere, you can declare the permission with maxSdkVersion attribute in your AndroidManifest.xml:

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" />`

**Comment by sanathkukkillaya** [comment]
Thanks a lot for your quick clarification. I now understand why we need to check for permission. Also thanks for the tip for using maxSdkVersion. That was exactly what I was looking for.

I checked in iOS also, and yeah, it does ask for permission. So everything's good.

Just for my curiosity, I had previously tried saving a file in Android 10 using File.WriteAllBytes, but it used to fail without permission. So how are you able to save to Gallery without any permission? Is there any special privilege since we are saving to DCIM?

**Comment by yasirkula** [comment]
Native MediaStore API doesn't require permission while saving media files on Android 10+ ([source](https://developer.android.com/training/data-storage/shared/media#storage-permission)).
