### ISSUE TITLE
Android: Duplicate class found

### ISSUE THREAD

**Issue by derwaldgeist** [yasirkula/UnityNativeGallery#188]
Since I upgraded Native Gallery to the latest version, I am getting build errors on Android:

```
Duplicate class com.yasirkula.unity.NativeGallery found in modules NativeGallery.jar (NativeGallery.jar) and classes.jar (:NativeGallery:)
Duplicate class com.yasirkula.unity.NativeGalleryMediaPickerFragment found in modules NativeGallery.jar (NativeGallery.jar) and classes.jar (:NativeGallery:)
Duplicate class com.yasirkula.unity.NativeGalleryMediaReceiver found in modules NativeGallery.jar (NativeGallery.jar) and classes.jar (:NativeGallery:)
Duplicate class com.yasirkula.unity.NativeGalleryPermissionFragment found in modules NativeGallery.jar (NativeGallery.jar) and classes.jar (:NativeGallery:)
Duplicate class com.yasirkula.unity.NativeGalleryPermissionReceiver found in modules NativeGallery.jar (NativeGallery.jar) and classes.jar (:NativeGallery:)
```

**Comment by derwaldgeist** [comment]
I think the problem is that after the update, there are two class bundles: `NativeGallery.jar` and `NativeGallery.aar`.

**Comment by yasirkula** [comment]
You can safely delete NativeGallery.**jar**.

**Comment by derwaldgeist** [comment]
Yes, I did this. But I would recommend adding this as an update note to the docs, since it is not obvious.

**Comment by yasirkula** [comment]
I had a code [that automatically removed NativeGallery.jar](https://github.com/yasirkula/UnityNativeGallery/blob/c825a03c51555d0d33556554bb822f525fd0eef2/Plugins/NativeGallery/Editor/NGPostProcessBuild.cs#L22-L31) but removed that code with the latest update because it gets called after every assembly reload. It has been 8 months since I've originally removed NativeGallery.jar and I think it was enough time for the majority of the users to update the plugin. So the code has served its purpose in that time and has now retired 😸 For the remaining users, I'm happy to assist them with this error manually, no need to add a notice to README for this after 8 months.
