### ISSUE TITLE
[iOS] LoadImageAtPath texture has dimensions 1x1

### ISSUE THREAD

**Issue by mmeranerKodomo** [yasirkula/UnityNativeGallery#193]
**Description of the bug**

Hi there,
first of all, thank you for providing this plugin! I really appreciate it!

I am using NativeGallery for iOS development and want to read an image from the gallery, then display it in my app.
Everything works fine in the Unity Editor, but as soon as I try it on my device (iPhone 12 Pro, iOS 14.4.2, also tested it on an  iPhone 6, iOS 12.5.1), the picked image only has only one color and if I check the dimensions of the texture returned from `LoadImageAtPath` it says width 1 and height 1.
It appears to receive a color from the gallery, because the color of the image in the app differs if I pick different photos. Permissions are working fine.

I combed through the issues list, but couldn't find a solution. Maybe you can help me?

I also managed to reproduce the issue in an empty project with the sample code function `private void PickImage( int maxSize )`.

**Platform specs**

- Unity version: 2020.3.2f1
- Platform: iOS
- Device: iPhone 12 Pro, iOS 14.4.2 / iPhone 6, iOS 12.5.1
- Downloaded from the Asset Store

**Comment by yasirkula** [comment]
Hi! Can you see any error messages in Xcode console? Can you verify that maxSize isn't set to 1? What does SystemInfo.maxTextureSize return?

**Comment by yasirkula** [comment]
What do the values of NativeGallery.GetImageProperties return for the picked image's path?

**Comment by mmeranerKodomo** [comment]
Yes I can load it with `LoadImage`!
Now merely the rotation is wrong, but I can fix that by using the orientation and shuffling the pixels around.

**Comment by yasirkula** [comment]
You shouldn't rely on LoadImage because it will generate huge Textures for HD images and as you said, there is also the rotation problem.

Does removing these lines have any effect on LoadImageAtPath: https://github.com/yasirkula/UnityNativeGallery/blob/0bc6c23925e899e44506f13061287b0f24735957/Plugins/NativeGallery/iOS/NativeGallery.mm#L1393-L1405

**Comment by mmeranerKodomo** [comment]
Unfortunately not. The texture is again 1x1.

**Comment by yasirkula** [comment]
This will require extensive debug logging, unfortunately. I can't do it myself since I can't reproduce the issue. Inside [this native function](https://github.com/yasirkula/UnityNativeGallery/blob/0bc6c23925e899e44506f13061287b0f24735957/Plugins/NativeGallery/iOS/NativeGallery.mm#L1365-L1415), can you log values of pretty much everything via calls like `NSLog( @"width: %@", width );`?

**Comment by mmeranerKodomo** [comment]
Managed to fix it. I don't know why, but I was using `NativeGallery.LoadImageAtPath(path, 1);` and the 1 did exactly what it was supposed to.
Still, no idea why it worked fine on the Unity editor, but all is fine now.

Thank you so much for your help!

**Comment by yasirkula** [comment]
> Can you verify that maxSize isn't set to 1?

It happens, lol. Editor functionality is limited in some aspects as you mentioned.
