### ISSUE TITLE
Photo natural orientation

### ISSUE THREAD

**Issue by Edorne** [yasirkula/UnityNativeGallery#20]
Hi,
Do you know how to get the orientation in which the photo was captured ?
Thanks

**Comment by yasirkula** [comment]
Theoretically, if the photo's width is greater than its height, it is captured in landscape orientation. Though, if you wish, you can use the `NativeGallery.GetImageProperties` function to get the EXIF orientation of an image (the width & height properties will return the size of the correctly oriented image). This will not work on iOS because plugin saves selected images in correct orientation before returning the path.

**Comment by Edorne** [comment]
I don't understand because, on Ios the photo's width and height returned by NativeGallery.GetImageProperties are always the same if i choose a landscape orientation's photo or not...

**Comment by yasirkula** [comment]
It should match the size (or aspect ratio) of the Texture2D that you would get using the NativeGallery.LoadImageAtPath function. Regardless of which orientation the image was captured in, the output image should always be in correct orientation and so should be the size.

I've tested it with [the pictures in this repo](https://github.com/recurser/exif-orientation-examples) and it always gave me the correctly oriented image and correct image size.

**Comment by Edorne** [comment]
Perfect ! Using the NativeGallery.LoadImageAtPath function, i get the correct Height et Width. It works well now. 
Thank you for your help !
