### ISSUE TITLE
Namespace issue? 

### ISSUE THREAD

**Issue by marck0zz** [yasirkula/UnityNativeGallery#202]
** Issue Description **
Namespace issue

Firts of all thanks a lot for the plugin, is a life saver!!! 

Then, this could be a configuration issue but I just can't solved it. I get this namespace error in my script (visual studio 2019) but in the Unity side nothing is promted in the console, forthermore, the project runs and works pretty good on android (tested on Galaxy Note9).

Here the evidence:

![NativeGalleryIssue](https://user-images.githubusercontent.com/11354912/122664402-c2ccc080-d166-11eb-8cdd-32bac7108584.png)

**Reproduction steps**

I have try both imported the plugin by package manager, adding the line in the "manifest.json" file and downloading the master zip project and copy the "Plugins" folder on "Assets Folder"

**Platform specs**

- Unity version: 2020.3.3
- Platform: Android
- Visual Studio 2019

As I say, the project works fine but the error on the script is very anoying.

Thanks in advance!

**Comment by yasirkula** [comment]
This isn't a NativeGallery error but rather a Visual Studio error (otherwise Unity would've thrown the error, as well) so I'm closing this issue. Regardless, you can try deleting all .csproj and .sln files from your project and then reopening Visual Studio. Or you can give these solutions a try: https://forum.unity.com/threads/intellisense-not-working-with-visual-studio-fix.836599/

**Comment by marck0zz** [comment]
Thanks lot. 

One of those solution worked for me, Generate csproj files and Generate project files was enough.

![imagen](https://user-images.githubusercontent.com/11354912/122790251-bf782880-d27d-11eb-92e9-fbb3839b7565.png)
