### ISSUE TITLE
iOS preprocessor directive in post build script

### ISSUE THREAD

**Issue by idamaeng** [yasirkula/UnityNativeGallery#208]
Hi,
would it be possible to remove the UNITY_IOS directives from NGPostProcessBuild in one of your next versions of the plugin? 

We have created a custom build pipeline for our project. If my editor is set to Android as current active platform and I trigger a  iOS build unity is switching to the unity platform and after a successful build switches back to Android. 
Because the starting platform is Android your code surrounded by UNITY_IOS is not included in the result of unity's compilation step and therefore never gets executed.

In my opinion (but I am not 100% sure) removing this directive should not be a problem, because your script is inside an Editor folder and has access to all assemblies during Editor time. 

Our project includes a post process build script too without this directive and it works like a charm.

Currently I removed UNITY_IOS from your script, which prevents me from easily updating your plugin. So I would be very grateful if you remove this directive.

Thank you!

**Comment by yasirkula** [comment]
I don't think PBXProject is visible in the editor if iOS platform isn't installed. For example, on my computer only Standalone and Android modules are installed and Unity doesn't recognize PBXProject in the editor. So if I remove UNITY_IOS, I won't be able to build my project, let alone test my project in Unity because the compiler errors won't let me.

I'd recommend you to report this issue as a bug to Unity because it seems like a serious bug on their end. When you programmatically switch to iOS, Unity should enable the `UNITY_IOS` directives. It's [documented](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html), after all.
