### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by troy-lamerton** [yasirkula/UnityNativeGallery#216]
This is great.

I would like to make the permission prompting optional.
Yes, this is possible, for example, the Reddit app doesn't require authorization.

The api usages would remain the same.

How to contribute to this repo?

Do I copy paste the Plugins folder into a larger Unity project, then I can iterate like that?

**Comment by yasirkula** [comment]
You can clone this repository using git and create a pull request with your changes. But I won't accept this pull request because I'm insistent on asking permissions to avoid any inconsistent behaviours on different devices (not all Android devices behave the same and I am not planning to deal with "Permissionless mode not working on X device" issues).
