### ISSUE TITLE
MetaData / Exif 

### ISSUE THREAD

**Issue by MrIThompson** [yasirkula/UnityNativeGallery#221]
Hello,
Thanks for the plugin, works a treat. 

Is there a method for pulling in the meta data with the image? 

Cheers,
Ian

**Comment by yasirkula** [comment]
What sort of metadata are you interested in?

**Comment by MrIThompson** [comment]
Hey, sorry missed this. 

I was looking to extract the location data (long, lat) 

Currently we are using [this](https://github.com/tedbarnett/read-exif-in-unity) but it's failing on iOs (as its built for JPG) 

Your plugin works great, so would appreciate it if it were in scope?

Cheers,
Ian

**Comment by yasirkula** [comment]
AFAIK, location data is stripped from picked photos unless Full Photos Permission is asked (and maybe Location permission, I'm not sure). This plugin doesn't ask that permission because it has a fatal issue with that permission. So I'm afraid you can't use this plugin to get location data from picked photos.
