### ISSUE TITLE
Camera recorded video shows only colors

### ISSUE THREAD

**Issue by dhanrajsinh24** [yasirkula/UnityNativeGallery#27]
When I grab any video that is recorded with the camera of the device, it is not playing properly and it shows only colors and sound but the actual video is not coming.

**Comment by yasirkula** [comment]
If you are using the VideoPlayer component, it is possible that Unity doesn't fully support that video format on that platform/device. If you are using `Handheld.PlayFullScreenMovie( "file://" + path );` on iOS and if your plugin is not [up-to-date](https://github.com/yasirkula/UnityNativeGallery/commit/245bc06b0142e7c59a239aea3db5695ae5ad0e29), try updating the plugin because the `[picker dismissViewControllerAnimated:NO completion:nil];` line in NativeGallery.mm might fix the problem. Otherwise, please let me know. It will be helpful to know the device/OS version you are testing on.

**P.S.** If you are not using VideoPlayer component, then try the following code and see if the issue persists with VideoPlayer, as well:

```csharp
NativeGallery.GetVideoFromGallery( ( path ) =>
{
	Debug.Log( "Video path: " + path );
	if( path != null )
	{
		// Play the video on a cube
		GameObject cube = GameObject.CreatePrimitive( PrimitiveType.Cube );
		cube.transform.position = Camera.main.transform.position + Camera.main.transform.forward * 2.5f;
		cube.transform.forward = -Camera.main.transform.forward;

		Material material = cube.GetComponent<Renderer>().material;
		if( !material.shader.isSupported ) // happens when Standard shader is not included in the build
			material.shader = Shader.Find( "Legacy Shaders/Diffuse" );

		AudioSource audioSouce = cube.AddComponent<AudioSource>();
		VideoPlayer videoPlayer = cube.AddComponent<VideoPlayer>();
		videoPlayer.renderMode = VideoRenderMode.MaterialOverride;
		videoPlayer.targetMaterialRenderer = cube.GetComponent<Renderer>();
		videoPlayer.targetMaterialProperty = "_MainTex";
		videoPlayer.audioOutputMode = VideoAudioOutputMode.AudioSource;
		videoPlayer.EnableAudioTrack( 0, true );
		videoPlayer.SetTargetAudioSource( 0, audioSouce );

		videoPlayer.url = path;
		videoPlayer.source = VideoSource.Url;
		videoPlayer.Play();
		audioSouce.Play();
	}
} );
```

**Comment by dhanrajsinh24** [comment]
Hi, thank you for your reply.

I already use VideoPlayer of Unity and Diffuse shader on a plane to play the video. All other videos are coming fine except camera recorded videos. So, the problem might be because the video format is not supported in VideoPlayer ?

**Comment by yasirkula** [comment]
+1 I can play recorded video via VideoPlayer smoothly on Galaxy S3.
