### ISSUE TITLE
Permission was Denied When i set to write permisson to Internal storage

### ISSUE THREAD

**Issue by ArigarasuthanRepo** [yasirkula/UnityNativeGallery#28]
When i take the screen shot with write permission as internal storage its shows an error permission denied.but i when i set to write permission as external storage its worked.How to take a screen shot using write permission as internal storage?

**Comment by yasirkula** [comment]
You can use the following code to take a screenshot and save it to persistentDataPath:

```csharp
private IEnumerator TakeScreenshotAndSave()
{
	yield return new WaitForEndOfFrame();

	Texture2D ss = new Texture2D( Screen.width, Screen.height, TextureFormat.RGB24, false );
	ss.ReadPixels( new Rect( 0, 0, Screen.width, Screen.height ), 0, 0 );
	ss.Apply();

	// Save the screenshot
	System.IO.File.WriteAllBytes( System.IO.Path.Combine( Application.persistentDataPath, "image.png" ), ss.EncodeToPNG() );
}
```

As you can see, this code doesn't depend on NativeGallery. If you want to use the Save/Get functions of NativeGallery, you'll have to set the permission to external storage because Gallery itself is located at external storage.

**Comment by ArigarasuthanRepo** [comment]
Thank you for the immediate response.I will check it.

**Comment by ArigarasuthanRepo** [comment]
It does not save the persistantpath.

**Comment by yasirkula** [comment]
To get the absolute path of the saved image, use the following code:

`Debug.Log( System.IO.Path.Combine( Application.persistentDataPath, "image.png" ) );`

Otherwise, are you getting an error message?

P.S. This script won't save the image to Gallery but only to the local storage. If you want to save the image to Gallery, you need to give External Storage permission and use NativeGallery.SaveImageToGallery function.

**Comment by ArigarasuthanRepo** [comment]
I was checked this path but no  files were found

**Comment by yasirkula** [comment]
Make sure to call TakeScreenshotAndSave as a coroutine: `StartCoroutine( TakeScreenshotAndSave() );`

If this is already the case, then File.WriteAllBytes function is malfunctioning. You should check the logs for error messages.

**Comment by ArigarasuthanRepo** [comment]
Ok Thank you..its worked

**Comment by ArigarasuthanRepo** [comment]
Is there any property in to find image saved path in Native Gallery Plugin?

**Comment by yasirkula** [comment]
On Android only, if your _filenameFormatted_ doesn't contain a {0}, you can get the save path by changing the visibility of `NativeGallery.GetSavePath` to public and then calling it.

**Comment by ArigarasuthanRepo** [comment]
Changed GetSavePath to public but its ask two parameters one is albumname  another one is filenameformatted. i was provided album name but how to get filename formatted?

**Comment by ArigarasuthanRepo** [comment]
Thank you so much it's worked fine.

**Comment by yasirkula** [comment]
Glad it worked!
