### ISSUE TITLE
Replacing files

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#29]
Hi! I know your plugin can handle the situation when a file with the same name exists. It performs action automatically by developer's descision. But general behaviour is to ask a user to overwrite or not.
My suggestion is to make GetSavePath public so developer could check if file exists and promt user to overwrite an image.

**Comment by yasirkula** [comment]
My main reason to keep GetSavePath private is to avoid confusion because it may not behave as expected in some cases; e.g.:

- on iOS, the result of GetSavePath is only used temporarily and it doesn't represent the actual path of the saved image/video, which is internal to Photos app. There is also no way to overwrite images in iOS because Photos internally handles collisions
- on Android, because of the fact that GetSavePath returns a unique path if filenameFormatted contains a {0}, if user calls GetSavePath after SaveImageToGallery/SaveVideoToGallery and not before, the returned path will not be pointing to the recently saved image/video

Thus, I prefer to keep the plugin simple and unambiguous.
