### ISSUE TITLE
Add WebGL and other platform support

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#37]
Add WebGL and other platform support?

**Comment by yasirkula** [comment]
For standalone platforms, you can use this plugin to show a file picker: https://github.com/yasirkula/UnitySimpleFileBrowser

It doesn't support WebGL because that platform doesn't have direct access to local file system. But this asset uses a workaround for WebGL to handle file uploads/downloads: https://github.com/gkngkc/UnityStandaloneFileBrowser. You can modify its code to your needs to support WebGL.

I don't know how to access the local file system on UWP yet but there might be a solution on the internet for this, as well.

**Comment by yosun** [comment]
It would be nice if these are all combined into a single solution

**Comment by yasirkula** [comment]
But I don't think that combination should be the NativeGallery plugin, as it is solely intended to access the Gallery. This is not the case for SimpleFileBrowser.

IMO, the best way to combine them all together would be to create a small manager script and use platform specific directives, like this:

```csharp
#if UNITY_EDITOR || UNITY_STANDALONE
// Use SimpleFileBrowser
#elif UNITY_ANDROID || UNITY_IOS
// Use NativeGallery
#else
// Platform not supported
#endif
```

**Comment by yosun** [comment]
Problem has to do with plugin conflicts.
Also iOS build and needing to manually remove non-iOS plugins for the build to be accepted by App Store. I guess there is probably some way to have a postprocess script remove things.

**Comment by yasirkula** [comment]
I'm putting extra effort to keep my plugins compatible with each other and with other plugins. In this case, at least NativeGallery and SimpleFileBrowser should be compatible with each other :D

But I'm surprised to hear non-iOS plugins being exported to Xcode project. I thought only plugins inside iOS folders were exported.

Regardless, I can write an example wrapper (manager) script for NativeGallery+SimpleFileBrowser combination, if you want. But you'll have to manage WebGL on you own.
