### ISSUE TITLE
Video capture

### ISSUE THREAD

**Issue by Hannessa** [yasirkula/UnityNativeGallery#5]
This is a really nice plugin, thanks a lot! How would you recommend doing video capture (with audio) to generate the byte stream for NativeGallery.SaveVideoToGallery()?

I've seen some different solutions such as using the native android.media.projection or using FFMPEG bindings, or even construct it manually by capturing a lot of screenshots using Texture2D.ReadPixels(). What do you think would be the best solution?

**Comment by yasirkula** [comment]
I think Everyplay is a good video recording solution, considering its wide range of supported devices and the scarcity of the screen recording plugins out there for mobile devices.

Everyplay generates an mp4 file rather than a byte stream but that shouldn't be a problem as you can use SaveVideoToGallery with existingMediaPath. However, you have to programmatically copy the recorded video to your local file system. Luckily, I had actually created a plugin just for this task, lol: https://github.com/yasirkula/UnityEveryplaySaveToLocal

**Comment by yosun** [comment]
do you know if everyplay works with ARKit? 
also, does it force the everyplay media upload screen?

**Comment by yasirkula** [comment]
It worked with Vuforia AR but I haven't tested it with ARKit. However, it looks like the microphone input is not captured. In normal circumstances, it is not possible to share the video without showing the media upload screen but with the help of UnityEveryplaySaveToLocal plugin, it is not necessary.

On iOS, there is also [ReplayKit API](https://docs.unity3d.com/ScriptReference/Apple.ReplayKit.ReplayKit.html), which does capture microphone input. But recorded videos have considerably larger size than Everyplay's recorded videos.
