### ISSUE TITLE
SaveImageToGallery return value

### ISSUE THREAD

**Issue by Jur-Wind** [yasirkula/UnityNativeGallery#54]
Hi,

Is it possible to add a return value for SaveImageToGallery. The path + filename on Android and the PHObjectPlaceholder localIdentifier on iOS?

Jur

**Comment by yasirkula** [comment]
But how are you gonna use PHObjectPlaceholder in Unity C#?

**Comment by Jur-Wind** [comment]
The method localIdentifier of PHObjectPlaceholder returns a string

**Comment by WarderFirst** [comment]
Hi, 
You can just break encapsulation and make this method public 
NativeGallery.GetSavePath(fileAlbum, filename);

This method return string with absolute path. It's work both Android & iOS.
We are using this for sharing photos

**Comment by Jur-Wind** [comment]
I understand but i need the localIdentifier on iOS and not the path to the image:(

**Comment by yasirkula** [comment]
On iOS, images/videos are not really saved at GetSavePath. Photos app copies the file from that path to its internal path (which can't be accessed via File functions), so the image is stored at some internal directory. On Android, if filenameFormatted contains {0} in it, GetSavePath should be called before SaveImageToGallery to get the correct path. For these reasons, I've kept GetSavePath private.

**For now**, I don't plan to add this feature to the plugin because I don't think the localIdentifier will be useful for most of the users. But this identifier can probably be found by replacing this code:

https://github.com/yasirkula/UnityNativeGallery/blob/d9c8df2d867ed9d8c6b74ed04c295f05b7cce8ca/Plugins/NativeGallery/iOS/NativeGallery.mm#L249-L270

Like this:

```objectivec
void (^saveBlock)(PHAssetCollection *assetCollection) = ^void(PHAssetCollection *assetCollection) {
	PHObjectPlaceholder *placeholder = nil;
	[[PHPhotoLibrary sharedPhotoLibrary] performChanges:^{
		PHAssetChangeRequest *assetChangeRequest;
		if (isImage)
			assetChangeRequest = [PHAssetChangeRequest creationRequestForAssetFromImageAtFileURL:[NSURL fileURLWithPath:path]];
		else
			assetChangeRequest = [PHAssetChangeRequest creationRequestForAssetFromVideoAtFileURL:[NSURL fileURLWithPath:path]];
		
		placeholder = [assetChangeRequest placeholderForCreatedAsset];
		PHAssetCollectionChangeRequest *assetCollectionChangeRequest = [PHAssetCollectionChangeRequest changeRequestForAssetCollection:assetCollection];
		[assetCollectionChangeRequest addAssets:@[placeholder]];
	} completionHandler:^(BOOL success, NSError *error) {
		[[NSFileManager defaultManager] removeItemAtPath:path error:nil];
		
		if (success)
			UnitySendMessage("NGMediaSaveCallbackiOS", "OnMediaSaveCompleted", [self getCString:[placeholder localIdentifier]]);
		else {
			NSLog(@"Error creating asset: %@", error);
			UnitySendMessage("NGMediaSaveCallbackiOS", "OnMediaSaveFailed", [self getCString:[error localizedDescription]]);
		}	
	}];
};
```

This will send the localIdentifier to here: https://github.com/yasirkula/UnityNativeGallery/blob/d9c8df2d867ed9d8c6b74ed04c295f05b7cce8ca/Plugins/NativeGallery/iOS/NGMediaSaveCallbackiOS.cs#L24-L31

You can then use that identifier in the callback (maybe add a prefix like "NOT_ERROR" to the message so that you can distinguish an error callback from an identifier callback).

**Comment by mohsinkhan26** [comment]
1. So have you included this in your plugin?
2. Kindly return the link from saving function for Android and iOS

**Comment by yasirkula** [comment]
It is not implemented. The localIdentifier wouldn't be useful for most of the users because it is only useful in an Objective-C code. I've explained why the path of the image/video is not returned here: https://github.com/yasirkula/UnityNativeGallery/issues/54#issuecomment-453173630

**Comment by mrkizy** [comment]
> It is not implemented. The localIdentifier wouldn't be useful for most of the users because it is only useful in an Objective-C code. I've explained why the path of the image/video is not returned here: [#54 (comment)](https://github.com/yasirkula/UnityNativeGallery/issues/54#issuecomment-453173630)

it is useful, beacuse some social sdks need caller to send identifiler to public functions,such as tiktok share
