### ISSUE TITLE
PHPhotoLibrary to support GIF 

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeGallery#6]
iOS plugin should be updated to the newer save interface to support saving gif

**Comment by yasirkula** [comment]
I tested saving gif to Photos on an iOS 9 iPad mini and it actually worked for me. Gif wasn't animating on Photos but while trying to share it via e-mail, it was animating as an attachment in the mail application (see https://discussions.apple.com/message/31338486#message31338486). Does it not work for you? May I ask your iOS version and the device model?

**Comment by yosun** [comment]
iOS 11 - they have an Animated folder and support gif animation in album

**Comment by yosun** [comment]
(Grab my app and make some gif's! http://arkitty.com 

Ideally I'd like to just use your solution, but right now to save gif to photo album, I am using https://gist.github.com/yosun/89f256b66141ec914e2b54c66c91c798

**Comment by yasirkula** [comment]
Don't get me wrong but have you tried the updated version of the plugin? Because it does use PHPhotoLibrary in saveMediaNew function and I don't understand how the same code works on iOS 9 but not on iOS 11. I've tried it with both of these functions:

- `NativeGallery.SaveImageToGallery( byte[] mediaBytes, string album, string filenameFormatted )`
- `NativeGallery.SaveImageToGallery( string existingMediaPath, string album, string filenameFormatted )`

By the way, ARKitty does look lovely and I must say, what a brilliant AR idea 😺

**Comment by yosun** [comment]
So I tried swapping out with your library... some issues with x64 support (required for ARKit)


Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PHAssetCollection", referenced from:
      objc-class-ref in NativeGallery.o
  "_OBJC_CLASS_$_PHFetchOptions", referenced from:
      objc-class-ref in NativeGallery.o
  "_OBJC_CLASS_$_PHAssetCollectionChangeRequest", referenced from:
      objc-class-ref in NativeGallery.o
  "_kUTTypeMovie", referenced from:
      +[UNativeGallery pickMedia:savePath:] in NativeGallery.o
  "_OBJC_CLASS_$_PHAssetChangeRequest", referenced from:
      objc-class-ref in NativeGallery.o
  "_OBJC_CLASS_$_PHPhotoLibrary", referenced from:
      objc-class-ref in NativeGallery.o
  "_kUTTypeImage", referenced from:
      +[UNativeGallery pickMedia:savePath:] in NativeGallery.o
      +[UNativeGallery imagePickerController:didFinishPickingMediaWithInfo:] in NativeGallery.o
  "_kUTTypeVideo", referenced from:
      +[UNativeGallery pickMedia:savePath:] in NativeGallery.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yosun** [comment]
(also thanks! the original arkitty was super overengineered where i wanted to have the cat track real colors with a real laser pointer... and other issues with performance)

**Comment by yasirkula** [comment]
Try applying the **Other Linker Flags** step to everything under *PROJECT* and *TARGETS*. Clean and rebuild. If it doesn't work, and if your Deployment Target is at least *8.0*, try adding **Photos** and **MobileCoreServices** frameworks to **Link Binary With Libraries** in **Build Phases**. Then clean and rebuild again. Please let me know if any of these work.

P.S. Do you use pods in your project?

**Comment by yasirkula** [comment]
As a side note, I was able to save gif to Photos on iOS 11.2 iPhone simulator today.

**Comment by yosun** [comment]
is there a way to add these xcode settings to postprocessor or other automation

**Comment by yasirkula** [comment]
It seems possible. Though, I think it is better to tweak these settings manually because of two reasons:

- when integrating Unity to a native project (for example to an Ionic project), settings in Unity Xcode project are not applied to the native project. In that case, user has to know which settings to tweak after the integration
- as there are only a couple of steps involved, I believe it'd be better for user to know exactly which settings this plugin affects

**Comment by yosun** [comment]
it seems i have to do that every time i build - it does get a little annoying. maybe include an optional post processor that can be run to automate things "by default"

**Comment by yasirkula** [comment]
I may give it a shot in my spare time. For now, you can try it yourself using the PBXProject class.

**Comment by yasirkula** [comment]
I've added a post processor in the latest update. Let me know if it doesn't work for you.
