### ISSUE TITLE
GetSavePath alternative

### ISSUE THREAD

**Issue by hippogamesunity** [yasirkula/UnityNativeGallery#78]
Hi! I was using GetSavePath to get a full path to DCIM folder. After update there is no such function. How could I get save path now?

**Comment by yasirkula** [comment]
It is no longer possible, sorry. For reference, please examine this code: https://github.com/yasirkula/UnityNativeGallery/blob/ba3fbf4f4c2840d6ac2c1e1145ca14b7834660c0/JAR%20Source/NativeGallery.java#L72-L96

Starting with Android 10, I'm no longer using absolute paths to save the image. The MediaStore handles name collisions, absolute path to the DCIM folder and etc. It is impossible to use the File API on DCIM folder on Android 10+ anyways, so using workarounds to retrieve the path isn't really useful anymore on Android.

**Comment by hippogamesunity** [comment]
Sorry for unrelated question, do you know if it's possible to use File API Android 10+ after receiving permissions? I mean any of MediaStore alternatives. For example, if I want to make a file browser app.
In my case I have Gallery in Pixel Studio app, where all files from DCIM/Pixel Studio are shown. I have some specific extensions like PSP so I can't just use system File Browser dialog. Actually, Android 10 has become a big head pain for me with Pixel Studio =)

**Comment by yasirkula** [comment]
I've researched this topic a lot recently, without the `android:requestLegacyExternalStorage="true"` attribute (Google Play won't accept apps with this attribute in the near future), seems like File API won't work outside of _Application.temporaryCachePath_ and _Application.persistentDataPath_ (i.e. app's internal directories).

If possible, you can use persistentDataPath. Otherwise, you'll have to use _ACTION_OPEN_DOCUMENT_TREE_ and/or _ACTION_OPEN_DOCUMENT_ intents and some native functions to access the DCIM directory. I'm currently examining [this example repository](https://github.com/android/storage-samples/tree/master/ActionOpenDocumentTree) to see how I can add Android 10 support to my SimpleFileBrowser plugin.

**Comment by hippogamesunity** [comment]
Yes, I'm using 'requestLegacyExternalStorage' now and considering using 'persistentDataPath' after 'requestLegacyExternalStorage' will be removed. At the same time I use persistentDataPath on iOS, so it will be the same behaviour. The only reasons I use DCIM is that:
1) Saved images are shown in system Gallery
2) User artworks are not deleted after app uninstall.

BTW I also use your SimpleFileBrowser, so I'll watch for it! Anyway, thanks for great work!
