### ISSUE TITLE
Save to nested albums

### ISSUE THREAD

**Issue by BrahimHadriche** [yasirkula/UnityNativeGallery#79]
Is it possible to save a nested album? I think it should be possible, but not sure if this plugin supports it or not

**Comment by BrahimHadriche** [comment]
Yes, more like the "folder structure", you can create many sub folders, and then put the album there.

**Comment by BrahimHadriche** [comment]
Implementation wise, it would be interesting to handle sub folders through the path, that way, if `MyFolder/MySubFolder/MyAlbum` is provided as an album name, it would create the respective `PHAssetCollection` and `PHCollectionList` needed. On Android I guess this is done through creating subfolders.

**Comment by yasirkula** [comment]
I see, you are talking about iOS. I was thinking about Android and was confused since nested albums aren't possible on Android. To be honest, I don't plan on implementing this feature since **1)** it is not multiplatform and **2)** you are the first person to mention nested albums since the plugin was released 2 years ago, so I don't think it is worth the effort to support nested albums.
