### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException String index out of range: -18

### ISSUE THREAD

**Issue by AndrewSpalato-FGMNT** [yasirkula/UnityNativeGallery#82]
`AndroidJavaException: java.lang.StringIndexOutOfBoundsException: String index out of range: -18
10-23 10:45:41.624 22236 22691 E Unity   : java.lang.StringIndexOutOfBoundsException: String index out of range: -18
10-23 10:45:41.624 22236 22691 E Unity   :      at java.lang.String.substring(String.java:2036)
10-23 10:45:41.624 22236 22691 E Unity   :      at com.yasirkula.unity.NativeGallery.SaveMedia(NativeGallery.java:104)
10-23 10:45:41.624 22236 22691 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
10-23 10:45:41.624 22236 22691 E Unity   :      at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
10-23 10:45:41.624 22236 22691 E Unity   :      at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
10-23 10:45:41.624 22236 22691 E Unity   :      at android.os.MessageQueue.next(MessageQueue.java:395)
10-23 10:45:41.624 22236 22691 E Unity   :      at android.os.Looper.loop(Looper.java:181)
10-23 10:45:41.624 22236 22691 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:32)
10-23 10:45:41.624 22236 22691 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0
10-23 10:45:41.624 22236 22691 E Unity   :   at UnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0
10-23 10:45:41.624 22236 22691 E Unity   :   at NativeGallery.SaveToGalleryInternal (System.String path, System.String album, NativeGallery+MediaType mediaType, NativeGallery+MediaS`

Hi, 

This is what I am getting when attempting to save a video to the android Gallery. I am able to access the file path but seem to be stuck here. Help will be appreciated.

Thanks!

**Comment by yasirkula** [comment]
This is a very interesting one. This happens on the following line: https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L104

Only a path like the following can cause this issue: `/directory.name.with.dot/videoNameWithoutExtension`. If this is the case, please try adding an extension to your video file.

**Comment by AndrewSpalato-FGMNT** [comment]
For context, the input path was `Application.peristentDataPath + "/Photo.png";`

**Comment by yasirkula** [comment]
https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L48-L51

https://github.com/yasirkula/UnityNativeGallery/blob/670d9e2b8328f7796dd95d29dd80fadd8935b804/JAR%20Source/NativeGallery.java#L104

Please let me know if you can see the problem here because I just can't.

**Comment by yasirkula** [comment]
Maybe if I can see your code, that would help.

**Comment by umiringo** [comment]
Hi, @yasirkula and @AndrewSpalato-FGMNT  :
I think this issue is triggered by **filename** but not path.
Because in NativeGallery.cs : 381
`string path = GetTemporarySavePath( filename );`
this path will passed to SaveToGalleryInternal as path.

If this path has no extension, for example:
 /storage/emulated/0/Android/data/com.umiringostudio.paintthewind/files/0080020

In this path, you have "." in your package name, so that the extension will be longer than filename which will cause a exception.

So I think the way to fix this is adding a extension name to your filename.

**Comment by yasirkula** [comment]
Yes, that makes sense 😄 Regardless, in the next update, I'll make sure that filenames without an extension don't throw StringIndexOutOfBoundsException. But will Gallery recognize media items without an extension? I don't think so.

**Comment by AndrewSpalato-FGMNT** [comment]
@yasirkula Turns out the plugin does not save files to camera roll/gallery from Application.temporaryCachePath (which is where the image was being initially saved to), fixed by copying file to PersistentData first and then worked, thought you should know.

**Comment by yasirkula** [comment]
That's unexpected. Plugin always copies the source image/video to a temporary location inside persistentDataPath first. Maybe you are not using the latest version of the plugin?

https://github.com/yasirkula/UnityNativeGallery/blob/6854eaffd772e7309fc19f89d8a72b65889f79f0/Plugins/NativeGallery/NativeGallery.cs#L437-L439
