### ISSUE TITLE
Retrieve file path for both iOS and Android

### ISSUE THREAD

**Issue by maherahmedraza** [yasirkula/UnityNativeGallery#89]
I am using the plugin to save the screenshot to the gallery in Unity application. But now I need to show the preview of the image or video saved in the gallery. After that I want to share the file using Native Share. So how should I get the file path to the saved file?

**Comment by yasirkula** [comment]
It is not possible. Here's a recent discussion about it: https://github.com/yasirkula/UnityNativeGallery/issues/78#issuecomment-541333226. If you want, you can keep a copy of the original file and preview/share it. If you are using the Save function with `string existingMediaPath` argument, then you can continue accessing existingMediaPath since NativeGallery saves a copy of that file to the Gallery.
