### ISSUE TITLE
Integration with Native Share

### ISSUE THREAD

**Issue by emanuelhm** [yasirkula/UnityNativeGallery#90]
Is it possible to save a image to gallery using this plugin and then get it's path in order to use it to share a image with Native Share?

**Comment by yasirkula** [comment]
It is not possible to fetch the path of the saved image. But here's a workaround:

- save the image to a temporary path in Application.temporaryCachePath
- save it to gallery via NativeGallery.SaveImageToGallery(imagePath, ...) 
- share it via NativeShare

You can't delete the temporary image immediately, though, since it is not possible to know whether or not NativeShare has finished sharing that file (there is no callback). But it should be fine if you always use the same temporary path in this process (there will only be 1 temporary image on disk and it will be deleted when the app is uninstalled or when OS decides to delete temporary files to free up some space).

**Comment by emanuelhm** [comment]
Thank you very much
